In [45]:
import os
from PIL import Image
import numpy as np

In [49]:
root_Dir = 'photos'
search = os.walk(root_Dir)
for dir_name,subList,file_names in search:
    print("Folder Name:", dir_name,"\nTotal Number of files: ",len(file_names),"\nFiles :\n")
    for name in file_names:
        print('\t',name)

Folder Name: photos 
Total Number of files:  19 
Files :

	 1.jpg
	 11.jpg
	 12.jpg
	 13.jpg
	 14.jpg
	 15.jpg
	 16.jpg
	 17.jpg
	 18.jpg
	 19.jpg
	 2.jpg
	 20.jpg
	 3.jpg
	 4.jpg
	 5.jpg
	 6.jpg
	 7.jpg
	 8.jpg
	 9.jpg


In [50]:
image_list = []
def main():
    for imgages in range(len(file_names)):
        image = Image.open(dir_name+'\\'+file_names[imgages])
        resized_image = image.resize((200,200))
        image_array = np.array(resized_image)
        image_list.append(image_array)
        image_list_array = np.array(image_list)
    print("Array size:",image_list_array.size,'\n')
    print("Array Dimension: ",image_list_array.ndim,'\n')
    print("Array Shape: ",image_list_array.shape,'\n')
    print("Array: ",image_list_array,'\n')


## Testing

In [51]:
if __name__ == '__main__':
    main()

Array size: 2280000 

Array Dimension:  4 

Array Shape:  (19, 200, 200, 3) 

Array:  [[[[  1   2   4]
   [  1   2   4]
   [  3   4   6]
   ...
   [ 23  19  16]
   [ 21  16  12]
   [ 21  14   8]]

  [[  1   2   4]
   [  1   2   4]
   [  2   3   5]
   ...
   [ 31  27  24]
   [ 34  29  25]
   [ 12   5   0]]

  [[  1   2   4]
   [  1   2   4]
   [  1   2   4]
   ...
   [ 16  12   9]
   [ 22  17  13]
   [ 18  11   5]]

  ...

  [[ 30  38  40]
   [ 52  57  60]
   [ 25  29  32]
   ...
   [ 71  50  31]
   [ 72  54  34]
   [ 62  46  21]]

  [[ 42  50  52]
   [ 25  30  33]
   [ 33  37  40]
   ...
   [ 72  51  32]
   [ 68  50  30]
   [ 70  54  29]]

  [[ 43  51  53]
   [ 48  53  56]
   [ 39  43  46]
   ...
   [ 76  55  36]
   [ 64  46  26]
   [ 73  57  32]]]


 [[[ 14  16  13]
   [ 11  13  10]
   [ 13  13  11]
   ...
   [  6   1   0]
   [ 19  13  13]
   [ 30  24  26]]

  [[ 15  17  14]
   [  9   9   7]
   [  8   8   6]
   ...
   [ 29  24  21]
   [ 18  12  12]
   [ 29  23  27]]

  [[ 21  20  18]
